# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./rbac.yaml
  - ./external-secret.yaml
helmCharts:
  - name: gitlab-agent
    repo: https://charts.gitlab.io
    releaseName: gitlab-agent
    version: 2.26.0
    namespace: maraude-restos
    valuesFile: ./values.yaml
