replicas: 1
config:
  secretName: gitlab-agent-auth
  kasAddress: wss://kas.gitlab.com
serviceAccount:
  create: false
  name: gitlab-agent-sa
rbac:
  create: false
  useExistingRole: gitlab-agent-role
