auth:
  username: postgres
  existingSecret: "postgres-auth"
  secretKeys:
    adminPasswordKey: "postgres-password"
primary:
  nodeSelector:
    kubernetes.io/hostname: oliver
  persistence:
    enabled: true
    existingClaim: "database-longhorn"
