apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-agent-credentials
  namespace: maraude-resto
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gitlab-agent-auth
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "157e4b66-81c1-48bc-8732-b40100cbb818"
