apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-agent-sa
  namespace: maraude-resto
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-agent-role
  namespace: maraude-resto
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-agent-rolebinding
  namespace: maraude-resto
subjects:
  - kind: ServiceAccount
    name: gitlab-agent-sa
    namespace: maraude-resto
roleRef:
  kind: Role
  name: gitlab-agent-role
  apiGroup: rbac.authorization.k8s.io
---

