apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-credentials
  namespace: home-assistant
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: home-assistant-credentials
    template:
      data:
        secrets.yaml: |
          oauth_id: "{{ .oauth_id }}"
          oauth_secret: "{{ .oauth_secret }}"
  data:
    - secretKey: oauth_id
      remoteRef:
        key: "ce1efeb3-6b91-487f-98ed-b41c00a43269"
    - secretKey: oauth_secret
      remoteRef:
        key: "ef1a185e-6248-4e0f-a1f2-b41c00a44743"
