# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./external-secret.yaml
  - ./route.yaml
helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    releaseName: home-assistant
    version: 0.3.56
    namespace: home-assistant
    valuesFile: ./values.yaml
