apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-credentials
  namespace: n8n
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-credentials
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: "199e65b3-b370-42a4-8d66-b40d00b85022"
    - secretKey: oidc-client-id
      remoteRef:
        key: "68a9a4d9-c116-4f1e-a98f-b40d0112aef7"
    - secretKey: oidc-client-secret
      remoteRef:
        key: "db9f9cef-c3be-4183-876c-b40d0112cf84"
