# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  storageClassName: "local-path-qualidata"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
