apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ferdium-credentials
  namespace: ferdium
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ferdium-credentials
    creationPolicy: Owner
  data:
    - secretKey: db-user
      remoteRef:
        key: "ae429042-b871-4bc9-a017-b43d00bcffc7"
    - secretKey: db-password
      remoteRef:
        key: "06269414-bac4-4d2c-9788-b43d00bdaa9a"
