# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-longhorn
  namespace: jellyfin
spec:
  storageClassName: "longhorn-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-rwx
  namespace: jellyfin
spec:
  storageClassName: "longhorn-hdd"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
---
