nodeSelector:
  kubernetes.io/hostname: oliver
persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config-longhorn
  media:
    enabled: true
    existingClaim: jellyfin-media-longhorn
