apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: forgejo-db-credentials
    template:
      data:
        database: |
          DB_TYPE = postgres
          HOST = "postgresql.database.svc.cluster.local:5432"
          NAME = forgejo
          USER = forgejo
          PASSWD = {{ .db_password }}
  data:
    - secretKey: db_password
      remoteRef:
        key: "79358091-9034-4df3-9255-b41900e31f33"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oauth-credentials
  namespace: forgejo
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: forgejo-oauth-credentials
    template:
      data:
        key: "{{ .oauth_id }}"
        secret: "{{ .oauth_secret }}"
  data:
    - secretKey: oauth_id
      remoteRef:
        key: "f8ee042e-bb43-4b1c-8cda-b41900eae592"
    - secretKey: oauth_secret
      remoteRef:
        key: "40bb1fd4-6f73-43e9-ab74-b41900eb90b5"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-signing-credentials
  namespace: forgejo
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: forgejo-signing-credentials
    template:
      data:
        privateKey: "{{ .gpg_key }}"
  data:
    - secretKey: gpg_key
      remoteRef:
        key: "b4bf8ff1-2f07-46aa-a0fb-b41900f56670"
---
