# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  storageClassName: "local-path-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
