apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: neffi-fr-cert
  namespace: envoy-gateway-system
spec:
  secretName: neffi-fr-tls
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.neffi.fr"
    - "neffi.fr"
