apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: database
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgres-auth
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: "34034005-1d45-4361-8bfe-b3ff012da61a"
