apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cert-manager-ovh-auth
    creationPolicy: Owner
  data:
    - secretKey: application-key
      remoteRef:
        key: "fc9f8144-e34c-455d-9fc6-b3fe01163ff7"
    - secretKey: application-secret
      remoteRef:
        key: "da0aa173-3391-4440-8869-b3fe011653da"
    - secretKey: consumer-key
      remoteRef:
        key: "17e5a53f-96c7-4b8b-a000-b3fe011673c8"
