---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["Neffi42/homelab"],
      "platform": "forgejo",
      "endpoint": "https://codeberg.org"
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 900
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: oliver
          containers:
            - image: renovate/renovate:43.168
              name: renovate-bot
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_BASE_DIR
                  value: "/tmp/renovate/"
                - name: RENOVATE_CONFIG_FILE
                  value: "/opt/renovate/config.json"
                - name: RENOVATE_PR_HOURLY_LIMIT
                  value: "15"
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-credentials
                      key: pat
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
