apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nextcloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: '63dfbd95-8b7c-4925-97cb-b405000843e3'
    - secretKey: db-password
      remoteRef:
        key: 'b6ffba82-0a80-49be-92f1-b40400935b02'
    - secretKey: admin-username
      remoteRef:
        key: '1468ef5a-38d0-43f2-8833-b40500ab21e2'
    - secretKey: admin-password
      remoteRef:
        key: 'a3c5d32e-d485-454c-a015-b40500ab398c'
