# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  storageClassName: "local-path-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---

