nodeSelector:
  kubernetes.io/hostname: oliver
nextcloud:
  host: "nextcloud.neffi.fr"
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: admin-username
    passwordKey: admin-password
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql.database.svc.cluster.local:5432
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: db-username
    passwordKey: db-password
extraEnv:
  - name: NEXTCLOUD_TRUSTED_DOMAINS
    value: "nextcloud.neffi.fr localhost"
  - name: TRUSTED_PROXIES
    value: "10.42.0.0/16 10.0.0.0/8"
  - name: APACHE_DISABLE_REWRITE_IP
    value: 1
  - name: OVERWRITEHOST
    value: "nextcloud.neffi.fr"
  - name: OVERWRITEPROTOCOL
    value: "https"
  - name: OVERWRITECONDADDR
    value: "^10\\.42\\..*"
persistence:
  enabled: true
  existingClaim: nextcloud-longhorn
livenessProbe:
  initialDelaySeconds: 30
readinessProbe:
  initialDelaySeconds: 30
