internalDatabase.enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql:5432
  existingSecret:
    secretName:
    enabled: true
    passwordKey: password
configs:
  oidc.config.php: |-
    <?php
    $CONFIG = array (
      'oidc_login_provider_url' => 'https://auth.yourdomain.com/application/o/nextcloud/',
      'oidc_login_client_id' => 'your-authentik-client-id',
      'oidc_login_client_secret' => 'your-authentik-client-secret',
      'oidc_login_auto_redirect' => true,
      'oidc_login_button_text' => 'Log in with Authentik',
      'oidc_login_hide_password_form' => true,
      'oidc_login_use_id_token' => true,
    );
