apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-credentials
  namespace: jellyfin
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: vpn-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "05314bcd-55b8-46eb-ab61-b4430168eeae"
    - secretKey: password
      remoteRef:
        key: "ca3afbc6-afce-4092-bf88-b4430169039d"
