# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-longhorn
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn-hdd"
  resources:
    requests:
      storage: 2Gi
---
