apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: argocd
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: "42d807af-bfce-4af9-bbb1-b3fd017b4b46"
  target:
    name: argocd-repo-auth
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "https://codeberg.org/Neffi42/homelab"
        username: "Neffi42"
        password: "{{ .token }}"
