apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pi-hole-credentials
  namespace: pi-hole
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pi-hole-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-password
      remoteRef:
        key: "8f9bbe46-75ac-4567-98e9-b43d0105e3fd"
