apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pi-hole
  name: pi-hole
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
